version: "3.3"
services:
  app:
      build:
         context: .
         dockerfile: Dockerfile
         args:
           eurekaIp: ${EUREKA_IP}
      image: zuul-gateway-application
      ports:
        - "8080:8080"