version: "3.3"
services:
  app:
      build:
         context: .
         dockerfile: Dockerfile-dev
         args:
           eurekaIp: ${EUREKA_IP}
      image: products-application
      ports:
        - "8070:8070"